/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aula1.Visao;

import aula1.Controlador.PedidoController;
import aula1.Controlador.UsuarioController;
import com.google.gson.Gson;
import com.google.gson.JsonObject;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Italo
 */
public class Pedido extends javax.swing.JFrame {

    private JsonObject codigoToUsuario;
    private JsonObject usuarioToCodigo;

    /**
     * Creates new form Pedido
     */
    public Pedido() {
        initComponents();
        desabilitarComponentes();
        carregarCategorias();
        carregarTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textCodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textData = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textDescricao = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        textValor = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePedidos = new javax.swing.JTable();
        buttonNovo = new javax.swing.JButton();
        buttonEditar = new javax.swing.JButton();
        buttonExcluir = new javax.swing.JButton();
        buttonSalvar = new javax.swing.JButton();
        buttonCancelar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        comboUsuario = new javax.swing.JComboBox<>();
        btnProdutos = new javax.swing.JButton();
        btnRecalcular = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Pedidos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jLabel2.setText("Código");

        textCodigo.setEditable(false);

        jLabel3.setText("Data");

        jLabel4.setText("Descrição");

        jLabel5.setText("Valor total");

        tablePedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Descrição", "Valor total", "Data", "Usuário"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablePedidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePedidosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablePedidos);
        if (tablePedidos.getColumnModel().getColumnCount() > 0) {
            tablePedidos.getColumnModel().getColumn(0).setMaxWidth(100);
        }

        buttonNovo.setText("Novo");
        buttonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNovoActionPerformed(evt);
            }
        });

        buttonEditar.setText("Editar");
        buttonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditarActionPerformed(evt);
            }
        });

        buttonExcluir.setText("Excluir");
        buttonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExcluirActionPerformed(evt);
            }
        });

        buttonSalvar.setText("Salvar");
        buttonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSalvarActionPerformed(evt);
            }
        });

        buttonCancelar.setText("Cancelar");
        buttonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelarActionPerformed(evt);
            }
        });

        jLabel6.setText("Usuário");

        comboUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnProdutos.setText("Produtos");
        btnProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdutosActionPerformed(evt);
            }
        });

        btnRecalcular.setText("Recalcular");
        btnRecalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecalcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textDescricao))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(buttonNovo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buttonEditar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buttonExcluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buttonSalvar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonCancelar)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboUsuario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(textData, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textValor, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRecalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(textData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(comboUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(textDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProdutos)
                    .addComponent(jLabel5)
                    .addComponent(textValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRecalcular))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonNovo)
                    .addComponent(buttonEditar)
                    .addComponent(buttonExcluir)
                    .addComponent(buttonSalvar)
                    .addComponent(buttonCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablePedidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePedidosMouseClicked
        int linha = tablePedidos.getSelectedRow();
        if (linha == -1) {
            return;
        }

        DefaultTableModel m = (DefaultTableModel) tablePedidos.getModel();

        String codigo = m.getValueAt(linha, 0).toString();
        String json = PedidoController.recuperar(codigo);

        JsonObject dados = new Gson().fromJson(json, JsonObject.class);

        textCodigo.setText(dados.get("codigo").getAsString());
        textDescricao.setText(dados.get("descricao").getAsString());
        textValor.setText(dados.get("valorTotal").getAsString());
        textData.setText(dados.get("dataCriacao").getAsString());
        comboUsuario.setSelectedItem(codigoToUsuario.get(dados.get("codigoUsuario").getAsString()).getAsString());
    }//GEN-LAST:event_tablePedidosMouseClicked

    private void buttonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNovoActionPerformed
        limparComponentes();

        SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        String data = df.format(new Date());
        textData.setText(data);

        habilitarComponentes();
    }//GEN-LAST:event_buttonNovoActionPerformed

    private void buttonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditarActionPerformed
        int linha = tablePedidos.getSelectedRow();
        if (linha == -1) {
            return;
        }

        habilitarComponentes();
    }//GEN-LAST:event_buttonEditarActionPerformed

    private void buttonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExcluirActionPerformed
        desabilitarComponentes();

        int linha = tablePedidos.getSelectedRow();
        if (linha == -1) {
            return;
        }

        DefaultTableModel m = (DefaultTableModel) tablePedidos.getModel();

        String codigo = (String) m.getValueAt(linha, 0);
        PedidoController.excluir(codigo);

        m.removeRow(linha);
        limparComponentes();

        JOptionPane.showMessageDialog(this, "Operação executada com sucesso", "Sucesso",
                JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_buttonExcluirActionPerformed

    private void buttonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSalvarActionPerformed
        desabilitarComponentes();

        salvar();
    }//GEN-LAST:event_buttonSalvarActionPerformed

    private void buttonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelarActionPerformed
        limparComponentes();
        desabilitarComponentes();
    }//GEN-LAST:event_buttonCancelarActionPerformed

    private void btnProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdutosActionPerformed
        if (textCodigo.getText().trim().isEmpty() || textCodigo.getText().trim().equals("0")) {
            return;
        }
        new ProdutoPedido(textCodigo.getText()).setVisible(true);
    }//GEN-LAST:event_btnProdutosActionPerformed

    private void btnRecalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecalcularActionPerformed
        if (textCodigo.getText().equals("0")) {
            return;
        }

        String json = PedidoController.recalcularValorTotal(textCodigo.getText());
        JsonObject dados = new Gson().fromJson(json, JsonObject.class);

        if (dados.has("valorTotal")) {
            textValor.setText(dados.get("valorTotal").getAsString());
            salvar();
        }
    }//GEN-LAST:event_btnRecalcularActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProdutos;
    private javax.swing.JButton btnRecalcular;
    private javax.swing.JButton buttonCancelar;
    private javax.swing.JButton buttonEditar;
    private javax.swing.JButton buttonExcluir;
    private javax.swing.JButton buttonNovo;
    private javax.swing.JButton buttonSalvar;
    private javax.swing.JComboBox<String> comboUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablePedidos;
    private javax.swing.JTextField textCodigo;
    private javax.swing.JTextField textData;
    private javax.swing.JTextField textDescricao;
    private javax.swing.JTextField textValor;
    // End of variables declaration//GEN-END:variables

    private void configurarComponentes(boolean ativo) {
        textDescricao.setEditable(ativo);
        textData.setEditable(ativo);
        textValor.setEditable(ativo);
        comboUsuario.setEnabled(ativo);

        buttonNovo.setEnabled(!ativo);
        buttonEditar.setEnabled(!ativo);
        buttonSalvar.setEnabled(ativo);
        buttonCancelar.setEnabled(ativo);

        tablePedidos.setEnabled(!ativo);
    }

    private void desabilitarComponentes() {
        configurarComponentes(false);
    }

    private void habilitarComponentes() {
        configurarComponentes(true);
    }

    private void carregarTabela() {
        DefaultTableModel m = (DefaultTableModel) tablePedidos.getModel();
        m.setRowCount(0);

        List<String> colecao = PedidoController.recuperarTodos();

        for (String json : colecao) {
            JsonObject dados = new Gson().fromJson(json, JsonObject.class);
            Object[] linha = {
                dados.get("codigo").getAsString(),
                dados.get("descricao").getAsString(),
                dados.get("valorTotal").getAsString(),
                dados.get("dataCriacao").getAsString(),
                codigoToUsuario.get(dados.get("codigoUsuario").getAsString()).getAsString()
            };
            m.addRow(linha);
        }
    }

    private void limparComponentes() {
        textCodigo.setText("0");

        textDescricao.setText("");
        textValor.setText("0");
        textData.setText("");
        comboUsuario.setSelectedIndex(0);

        tablePedidos.clearSelection();
    }

    private void carregarCategorias() {
        String jsonUsuarioToCodigo = UsuarioController.usuarioToCodigo();
        usuarioToCodigo = new Gson().fromJson(jsonUsuarioToCodigo, JsonObject.class);

        String jsonCodigoToUsuario = UsuarioController.codigoToUsuario();
        codigoToUsuario = new Gson().fromJson(jsonCodigoToUsuario, JsonObject.class);

        comboUsuario.removeAllItems();

        for (String cat : usuarioToCodigo.keySet()) {
            comboUsuario.addItem(cat);
        }
    }

    private void salvar() {
        int linha = tablePedidos.getSelectedRow();
        DefaultTableModel m = (DefaultTableModel) tablePedidos.getModel();

        if (linha == -1) {
            m.addRow(new Object[]{null, null, null, null, null});
            linha = m.getRowCount() - 1;
        }

        JsonObject dados = new JsonObject();
        dados.addProperty("codigo", textCodigo.getText());
        dados.addProperty("descricao", textDescricao.getText());
        dados.addProperty("dataCriacao", textData.getText());
        dados.addProperty("valorTotal", textValor.getText());
        String usuario = (String) comboUsuario.getSelectedItem();
        dados.addProperty("codigoUsuario", usuarioToCodigo.get(usuario).getAsString());
        String json = PedidoController.salvar(dados.toString());

        JsonObject result = new Gson().fromJson(json, JsonObject.class);

        if (result.has("mensagem")) {
            JOptionPane.showMessageDialog(this, result.get("mensagem").getAsString(),
                    "Erro", JOptionPane.ERROR_MESSAGE);
            habilitarComponentes();
            return;
        }

        m.setValueAt(result.get("codigo").getAsString(), linha, 0);
        m.setValueAt(textDescricao.getText(), linha, 1);
        m.setValueAt(textValor.getText(), linha, 2);
        m.setValueAt(textData.getText(), linha, 3);
        m.setValueAt(comboUsuario.getSelectedItem().toString(), linha, 4);
    }

}
